### ISSUE TITLE
Can the viewer be scroll

### ISSUE THREAD

**Issue by passerbyloo** [Dean177/react-native-json-tree#150]
if the json object expanded too long over the screen ,now can not scroll to see that content

**Comment by Dean177** [comment]
Have you tried wrapping with a `<ScrollView />`?

**Comment by money-development** [comment]
@Dean177 I would like to write that this problem is relevant. Of course, we use ScrollView, but the problem is that almost all internal tree elements don't perceive the event and therefore the content can only be scrolled by certain upper parts. I would also like to know if this library is still supported?

**Comment by Dean177** [comment]
Hey

> but the problem is that almost all internal tree elements don't perceive the event and therefore the content can only be scrolled by certain upper parts

I'm not sure what you mean by this? (Possibly a video might help?)


>  I would also like to know if this library is still supported?

I haven't updated the library in a long time since the things I needed it for haven't had to be updated. 
As such if there are issues with new versions of `react-native` they are unlikely to be fixed by me unless some other user provides a PR, in which case I am happy to review, merge and release a new version.
